
# Site settings
title: DataCards Documentation
description: Official documentation for the DataCards plugin for Obsidian
baseurl: "/data-cards"
url: "https://sophokles187.github.io"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Author information
author:
  name: Sophokles187
  url: https://github.com/Sophokles187

# Page defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
