# Site settings
title: DataCards Documentation
description: Official documentation for the DataCards plugin for Obsidian
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sophokles187.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - preview-instructions.md
  - README.md

# Plugins
plugins:
  - jekyll-seo-tag

# Include these files that are automatically excluded
include:
  - .nojekyll

# Custom variables
version: "1.0"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
